Repository FIWARE-Ops/marinera-e2e, pull requests merged in 2022-05, with the labels that each got.

#2 add more doc
  README.md
  src/test/java/org/fiware/marinerae2e/StepDefinitions.java
  src/test/resources/testDefinition/data_is_shown_in_grafana.feature
Labels: patch

#3 make service path configurable
  src/test/java/org/fiware/marinerae2e/StepDefinitions.java
Labels: patch

#4 Update sample time of every point
  src/test/java/org/fiware/marinerae2e/StepDefinitions.java
Labels: patch

#5 Add sec test
  README.md
  pom.xml
  src/test/java/org/fiware/marinerae2e/StepDefinitions.java
  src/test/resources/testDefinition/data_is_shown_in_grafana.feature
Labels: minor

#6 Add test scenario for Air Quality Monitoring App
  src/test/java/org/fiware/marinerae2e/StepDefinitions.java
  src/test/resources/testDefinition/data_is_shown_in_grafana.feature
Labels: minor

#7 work when nothing is to clean
  src/test/java/org/fiware/marinerae2e/StepDefinitions.java
Labels: patch

#10 Add aqapp test to the documentation
  README.md
Labels: documentation, patch
